### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by amichair**

### CODE REVIEW

**Comment by amichair** [comment]
Would it be possible to merge this PR and make a quick release? The dependencies have fallen quite far behind...

Maybe also bump the release version to 1.3.0 instead of 1.2.1.

**Comment by amichair** [comment]
Will there be a new release?

**Comment by amichair** [comment]
Anything I can do to help?

**Comment by skjolber** [comment]
@amichair sorry, I am drowning in github notifications and did not catch this

**Pull request merged**
